services:
  db:
    environment:
      POSTGRES_DB: moodle
      POSTGRES_PASSWORD: m@0dl3ing
      POSTGRES_USER: moodle
    image: postgres:13
  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - ./docker/assets/exttests/apache2_ports.conf:/etc/apache2/ports.conf:rw
      - ./docker/assets/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf:rw
  mailpit:
    environment:
      MP_WEBROOT: /_/mail/
    image: axllent/mailpit:v1.10
  selenium:
    image: selenium/standalone-firefox:3
    volumes:
      - .:/var/www/html:ro
  webserver:
    depends_on:
      db:
        condition: service_started
      mailpit:
        condition: service_started
    environment:
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: m@0dl3ing
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 127.0.0.1:8000
    image: moodlehq/moodle-php-apache:8.1
    ports:
      - 127.0.0.1:8000:80/tcp
    volumes:
      - ./docker/assets/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf:rw
      - ./docker/assets/web/apache2_mailpit.conf:/etc/apache2/conf-enabled/apache2_mailpit.conf:rw
      - .:/var/www/html:rw
